export const bankList = [
  { code: 'CMB', name: '招商银行' },
  { code: 'CZB', name: '浙商银行' },
  { code: 'BOC', name: '中国银行' },
  { code: 'ICBC', name: '中国工商银行' },
  { code: 'ABC', name: '中国农业银行' },
  { code: 'CBC', name: '中国建设银行' },
  { code: 'PSBC', name: '中国邮政储蓄银行' },
  { code: 'BOCM', name: '交通银行' },
  { code: 'PAB', name: '平安银行' },
  { code: 'CMSB', name: '中国民生银行' },
  { code: 'CEB', name: '中国光大银行' },
  { code: 'CCB', name: '中信银行' },
  { code: 'GDB', name: '广发银行' },
  { code: 'CIB', name: '兴业银行' },
  { code: 'HXB', name: '华夏银行' },
  { code: 'PSDB', name: '上海浦东发展银行' },
  { code: 'HFB', name: '恒丰银行' },
  { code: 'HSHB', name: '徽商银行' },
  { code: 'CBHB', name: '渤海银行' },
  { code: 'CHONGQINGB', name: '重庆三峡银行' },
  { code: 'BEA', name: '东亚银行' },
  { code: 'UOBS', name: '大华银行' },
];

// export const bankNames = {
//   CMB: '招商银行',
//   CZB: '浙商银行',
//   BOC: '中国银行',
//   ICBC: '中国工商银行',
//   ABC: '中国农业银行',
//   CBC: '中国建设银行',
//   PSBC: '中国邮政储蓄银行',
//   BOCM: '交通银行',
//   PAB: '平安银行',
//   CMSB: '中国民生银行',
//   CEB: '中国光大银行',
//   CCB: '中信银行',
//   GDB: '广发银行',
//   CIB: '兴业银行',
//   HXB: '华夏银行',
//   PSDB: '上海浦东发展银行',
//   HFB: '恒丰银行',
//   HSHB: '徽商银行',
//   CBHB: '渤海银行',
//   CHONGQINGB: '重庆三峡银行',
//   BEA: '东亚银行',
//   UOBS: '大华银行',
// };
